name: Discord Commits
on: [push]
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: Sniddl/discord-commits@v1.3
        with:
            webhook: https://discord.com/api/webhooks/894867511470882826/oYq5vzda8aYW--rCiplr2oLf6coFliS-FwxTsNKLEZ0n_8EPIdVwppQwY7Bkw0LXTqNi
